apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-sustain-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: