apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: riliadmin/sustain-indy-foods-server:4
        ports:
        - containerPort: 8008
        env:
        - name: DEBUG
          value: "0"
        - name: DJANGO_ALLOWED_HOSTS
          value: "www.sustainindyfoods.com sustainindyfoods.com"
        - name: PG_USER
          value: "postgres"
        - name: PG_DATABASE
          value: "sustain_prod"
        - name: PG_HOST
          value: "postgres-sustain-cluster-ip-service"
        - name: PG_PORT
          value: "5432"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secretkey
              key: SECRETKEY